In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sqlite3
from datetime import datetime

In [2]:
df = pd.read_pickle('Data/football.pkl')

In [3]:
df['Précipitations en mm'] = df['Précipitations en mm'].astype('float32')

In [4]:
df['Date'] = df['Année'].astype(str)+'-'+df['Mois'].astype(str)+'-'+df['Jour'].astype(str)

df['Date'] = df['Date'].astype('datetime64[ns]')
df['Date'] = df['Date'].apply(lambda x : x.strftime('%Y-%m-%d'))

In [5]:
df = df.drop(columns=['Année','Mois','Jour','Heure'])

In [6]:
df.reindex(columns=['Date','Equipe domicile', 'Equipe exterieure', 'Vainqueur',
       'Score domicile', 'Score extérieur', 'Buteurs', 'Lieu du match',
       'Journée', 'Région', 'Temperature moyenne', 'Précipitations en mm'])

,Date,Equipe domicile,Equipe exterieure,Vainqueur,Score domicile,Score extérieur,Buteurs,Lieu du match,Journée,Région,Temperature moyenne,Précipitations en mm
0,2020-08-21,Bordeaux,Nantes,ex-aequo,0,0,[None],Bordeaux,1,aquitaine,22.5,5.0
1,2020-08-22,Dijon,Angers,exterieur,0,1,[I. Traoré],Dijon,1,bourgogne,22.0,19.0
2,2020-08-22,Lille,Rennes,ex-aequo,1,1,"[J. Bamba, D. Da Silva]",Lille,1,nord-pas-de-calais,19.0,1.0
3,2020-08-23,Monaco,Reims,ex-aequo,2,2,"[A. Disasi, B. Badiashile, B. Dia, E. Touré]",Monaco,1,provence-alpes-c-te-d-azur,25.5,1.0
4,2020-08-23,Lorient,Strasbourg,domicile,3,1,"[Y. Wissa, A. Grbic, P. Hamel, M. Chahiri]",Lorient,1,bretagne,17.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
375,2021-05-23,Rennes,Nîmes,domicile,2,0,"[S. Guirassy, B. Bourigeaud]",Rennes,38,bretagne,10.0,2.0
376,2021-05-23,Nantes,Montpellier,exterieur,1,2,"[R. Kolo Muani, G. Laborde, A. Delort]",Nantes,38,pays-de-la-loire,12.0,1.0
377,2021-05-23,Saint-Étienne,Dijon,exterieur,0,1,[A. Kamara],Saint-Étienne,38,rh-ne-alpes,12.0,0.0
378,2021-05-23,Reims,Bordeaux,exterieur,1,2,"[E. Touré, Y. Adli, E. Kwateng]",Reims,38,champagne-ardenne,10.5,1.0
379,2021-05-23,Strasbourg,Lorient,ex-aequo,1,1,"[H. Diallo, T. Chalobah]",Strasbourg,38,alsace,12.0,2.0

In [7]:
con=sqlite3.connect('Data/final_db.sqlite')
cursor = con.cursor()

In [8]:
championship_list = ['Ligue1','France',2020, 2021]

In [9]:
cursor.execute("""
        INSERT INTO championships (name, country, start_year, end_year)
        VALUES (?, ?, ?, ?)""",
        championship_list)

con.commit()

In [10]:
df_teams = pd.read_csv('Data/teams.csv')
df_teams = df_teams.rename(columns={'Unnamed: 0' : 'Rank'})
df_teams['Rank'] = df_teams['Rank'].apply(lambda x: x+1)
df_teams

    Rank       Entraineur           Club
0      1       C. Galtier          Lille
1      2    M. Pochettino       Paris-SG
2      3         N. Kovac         Monaco
3      4          P. Bosz           Lyon
4      5      J. Sampaoli      Marseille
5      6       B. Genesio         Rennes
6      7         F. Haise           Lens
7      8     O. Dal Oglio    Montpellier
8      9         A. Ursea           Nice
9     10     F. Antonetti           Metz
10    11          C. Puel  Saint-Étienne
11    12      J-L. Gasset       Bordeaux
12    13       G. Baticle         Angers
13    14        O. Garcia          Reims
14    15       J. Stephan     Strasbourg
15    16     C. Pelissier        Lorient
16    17  M. Der Zakarian          Brest
17    18     A. Kambouaré         Nantes
18    19      P. Plancque          Nîmes
19    20       D. Linares          Dijon

In [11]:
teams_sql = []
for i in zip(df_teams['Club'], df_teams['Club'], df_teams['Entraineur'], df_teams['Rank']):
    teams_sql.append(i)

In [12]:
for team in teams_sql:
    con.execute("""INSERT INTO
            teams (name, city, coach_name, rank)
            VALUES (?, ?, ?, ?)""",
        team)

con.commit()

In [13]:
df_players = pd.read_csv('Data/teams_players.csv')
df_players = df_players.drop('Unnamed: 0', axis=1)
df_players = df_players.rename(columns={'Né\xa0le' : 'Birthday'})
df_players

    Numéro de mallot            Nom Pays  Birthday  Pos.   Club  Entraineur
0               30.0   L. Chevalier  FRA   6/11/01  Gar.  Lille  C. Galtier
1                1.0    O. Karnezis  GRE  11/07/85  Gar.  Lille  C. Galtier
2               16.0     M. Maignan  FRA   3/07/95  Gar.  Lille  C. Galtier
3                5.0      S. Botman  HOL  12/01/00  Déf.  Lille  C. Galtier
4               None  I. Bouleghcha  FRA   9/12/02  Déf.  Lille  C. Galtier
..               ...            ...  ...       ...   ...    ...         ...
619             None       M. Baldé  GUB   6/11/95  Att.  Dijon  D. Linares
620             None    E. Belhadji  FRA  23/06/01  Att.  Dijon  D. Linares
621             None     M. Chouiar  FRA  23/01/99  Att.  Dijon  D. Linares
622             None      M. Konaté  SEN   3/04/93  Att.  Dijon  D. Linares
623             None        J. Siwe  FRA  29/07/01  Att.  Dijon  D. Linares

[624 rows x 7 columns]

In [14]:
# df_contracts = pd.concat([df_teams, df_players], axis=1)
# df_contracts
df_teams

    Rank       Entraineur           Club
0      1       C. Galtier          Lille
1      2    M. Pochettino       Paris-SG
2      3         N. Kovac         Monaco
3      4          P. Bosz           Lyon
4      5      J. Sampaoli      Marseille
5      6       B. Genesio         Rennes
6      7         F. Haise           Lens
7      8     O. Dal Oglio    Montpellier
8      9         A. Ursea           Nice
9     10     F. Antonetti           Metz
10    11          C. Puel  Saint-Étienne
11    12      J-L. Gasset       Bordeaux
12    13       G. Baticle         Angers
13    14        O. Garcia          Reims
14    15       J. Stephan     Strasbourg
15    16     C. Pelissier        Lorient
16    17  M. Der Zakarian          Brest
17    18     A. Kambouaré         Nantes
18    19      P. Plancque          Nîmes
19    20       D. Linares          Dijon

In [15]:
array_players = []
for i in zip(df_players['Nom'], df_players['Pos.'], df_players['Birthday'], df_players['Pays']):
    array_players.append(i)

In [16]:
for player in array_players:
    con.execute("""INSERT INTO
            players (name, position, birthdate, nationality)
            VALUES (?, ?, ?, ?)""",
        player)

con.commit()

In [18]:

matches = []
for i in zip(df['Date'], df['Lieu du match'], df['Précipitations en mm'], df['Temperature moyenne'] ):
    matches.append(i)

In [19]:
for match in matches:
    con.execute("""INSERT INTO
            matchs (date, place, rainfall, temperature, championship_id )
            VALUES (?, ?, ?, ?, (SELECT id FROM championships WHERE id = 1))""",
        match)

con.commit()

In [20]:
cursor.execute("""INSERT INTO participations (team_id, championship_id) 
SELECT teams.id, championships.id 
FROM teams 
CROSS JOIN championships;""")
con.commit()

In [21]:
list_teams = list(df_teams['Rank'])
list_clubs = list(df_teams['Club'])

In [22]:
df_contracts = df_players.replace(list_clubs, list_teams)
df_contracts = df_contracts.reset_index()

In [23]:
list_teams

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [24]:
rank_list = list(df_teams['Rank'])
rank_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [25]:
list_contracts = []
for i in zip(df_contracts['index'], df_contracts['Club']):
    list_contracts.append(i)

In [26]:
for contract in list_contracts:
    cursor.execute("""INSERT INTO
                contracts (player_id, team_id)
                VALUES (?, ?)""", 
                (contract))
con.commit()

In [27]:
cursor.execute("""SELECT COUNT(*) FROM contracts""").fetchall()

[(624,)]

In [28]:
# cursor.execute("""SELECT * FROM players""").fetchall()

In [29]:
goals_df = pd.DataFrame(df, columns=['Date','Buteurs'])
goals_df = goals_df.reset_index()
goals_df['match_id'] = goals_df['index'].apply(lambda x :x+1)

In [30]:
df_test_finl = goals_df['Buteurs'].explode()

In [31]:
indiv_buteurs = pd.DataFrame(df_test_finl)
#goals_df['final_id'] = df_test_finl.index
indiv_buteurs = indiv_buteurs.reset_index()
indiv_buteurs['index']
indiv_buteurs['index'] = indiv_buteurs['index'].apply(lambda x : x+1)
# for i in indiv_buteurs['Buteurs']:
#     if i == None:
#         print(i)
#         i = 'Test'
#         indiv_buteurs['Buteurs'] = indiv_buteurs['Buteurs']
indiv_buteurs = indiv_buteurs.fillna(value='NONE')

In [32]:
goals_sql = []
for i in zip(indiv_buteurs['Buteurs'], indiv_buteurs['index']):
    goals_sql.append(i)

In [33]:
for player in goals_sql:
    try:
        cursor.execute(f"""SELECT id FROM players WHERE name = '{player[0]}'""")
        player_id = cursor.fetchone()[0]
        print(player_id)
    except:
        player_id = -1
    cursor.execute("""INSERT INTO
                goals (player_id, match_id)
                VALUES (?, ?)""",
                (player_id, player[1]))
con.commit()

386
15
155
74
72
432
437
502
499
500
457
570
525
591
267
267
197
228
228
118
48
327
334
118
602
118
118
225
165
233
266
266
15
539
549
582
327
327
358
72
519
528
150
128
128
204
233
212
212
246
334
324
24
578
582
175
175
154
164
499
502
197
189
204
401
513
527
80
91
545
150
204
197
371
169
163
89
64
47
45
218
232
232
226
401
513
531
529
512
496
301
301
432
450
559
556
321
312
147
24
541
30
154
175
176
301
611
601
232
228
582
204
89
71
89
457
465
406
386
395
531
528
502
104
62
62
41
66
66
48
50
64
386
197
207
246
261
549
573
12
19
30
519
373
371
358
301
301
301
500
155
411
432
108
141
620
177
64
41
64
59
423
500
502
501
150
126
466
454
119
121
121
89
235
557
545
378
519
396
300
321
257
267
269
30
15
26
22
176
390
395
127
63
63
64
64
432
432
435
432
296
316
366
373
466
465
266
30
118
121
108
121
89
197
552
155
154
529
51
64
59
235
268
257
255
298
130
414
465
89
93
95
95
15
12
203
226
232
63
47
155
514
513
527
30
30
203
415
207
207
422
432
189
432
302
620
591
398
401
401
402
391
378
545
257
74
80
119
119
97
365
95
95
81
64
64
529
510
527
531
324
557
299
215
232
232
233
466
465
206
573
119
22
22
24
25
129
139
139
267
260
464
176
150
141
145
545
66
63
46
357
121
113
206
398
401
392
236
80
93
95
527
527
267
620
603
620
336
26
145
147
206
204
235
39
63
64
25
22
94
395
392
365
459
466
465
471
296
118
121
121
150
145
89
211
197
235
215
233
529
531
431
453
464
279
300
559
623
489
500
502
15
8
358
119
22
29
299
289
466
465
270
265
437
432
422
541
545
118
117
97
519
64
63
162
176
138
191
203
197
370
338
330
300
296
150
132
267
118
119
121
108
525
509
233
232
95
192
385
360
313
338
575
573
155
164
177
166
206
207
528
370
411
432
429
248
258
501
499
575
623
620
623
233
232
29
26
30
121
119
115
46
64
50
63
398
402
142
80
95
309
334
501
478
74
83
95
80
75
531
529
465
466
465
470
118
185
118
207
195
30
385
385
327
63
141
147
226
166
164
118
102
63
62
59
30
75
95
92
466
216
549
278
267
373
373
501
432
432
422
333
229
232
95
89
89
145
581
581
44
529
164
166
549
197
370
346
358
465
15
25
431
299
490
501
478
601
620
64
66
62
64
242
75
88
92
370
370
395
299
296
435
600
465
25
119
106
106
119
334
573
121
104
371
229
195
197
333
488
502
501
66
66
529
527
296
292
302
297
392
394
402
573
427
22
556
75
95
137
22
29
25
177
489
292
233
464
454
528
530
115
47
59
64
89
89
257
207
189
150
149
324
557
488
118
121
118
531
519
370
579
582
581
83
83
83
95
278
381
269
267
233
233
228
236
600
623
25
25
64
62
48
63
268
431
207
115
228
229
89
89
501
501
334
338
282
464
464
396
559
549
378
573
581
509
527
115
108
118
333
437
545
141
235
235
175
196
203
603
267
284
298
570
573
479
478
8
26
6
80
75
177
267
245
371
282
297
63
64
64
56
92
95
402
396
183
206
492
492
313
591
545
8
465
149
121
108
395
313
334
207
206
267
265
567
529
531
527
607
25
25
59
448
235
499
559
416
411
422
119
336
149
150
137
508
591
232
183
193
297
282
164
502
269
623
370
370
367
48
557
559
92
88
80
90
302
173
177
175
261
267
265
455
187
196
227
233
235
370
432
557
492
21
591
573
120
117
64
56
47
64
81
95
89
89
25
183
115
401
235
432
416
175
175
552
266
266
346
370
449
466
465
488
336
334
127
129
30
12
469
64
59
63
55
232
233
233
149
138
133
177
197
205
206
203
501
336
336
336
332
370
509
591
92
89
89
118
115
118
24
232
173
177
175
141
131
131
501
501
64
64
62
334
327
193
197
598
608
573
459
95
93
92
541
118
118
435
141
149
141
336
528
528
281
64
64
62
255
262
265
233
204
187
582
177
177
170
159
166
608
465
536
545
502
501
501
501
362
89
120
8
30
25
30
145
450
66
45
204
30
12
372
620
298
292
598
297
279
573
591
435
434
502
494
519
559
545
549
555
232
327
309
95
89
118
106
111
30
30
25
555
549
557
108
115
113
113
496
338
465
471
233
232
233
583
573
582
268
255
247
531
531
395
403
402
86
175
66
66
64
45
63
89
83
74
591
591
115
118
115
108
120
149
149
149
398
385
370
363
465
465
502
479
294
555
557
545
557
395
25
30
519
64
121
121
266
247
253
296
149
175
164
557
233
232
52
437
357
353
466
490

In [34]:
df2 = df.replace(list_clubs, rank_list)

In [35]:
df2 = df2.reset_index()
df2['index'] = df2['index'].apply(lambda x : x+1)
df2 = df2.rename(columns={'index': 'id'})

In [36]:
match_home_teams_list = []
for i in zip(df2['id'], df2['Equipe domicile'],df2['Score domicile']):
    match_home_teams_list.append(i)

In [37]:
for match_team in match_home_teams_list:
    cursor.execute("""INSERT INTO match_teams (match_id, team_id, home, goal) 
                VALUES (?,?,?,?)""", 
                (match_team[0], match_team[1], True, match_team[2]))
con.commit()

In [38]:
match_away_teams_list = []
for i in zip(df2['id'], df2['Equipe exterieure'],df2['Score extérieur']):
    match_away_teams_list.append(i)

In [39]:
for match_team in match_away_teams_list:
    cursor.execute("""INSERT INTO match_teams (match_id, team_id, home, goal) 
                VALUES (?,?,?,?)""", 
                (match_team[0], match_team[1], False, match_team[2]))
con.commit()

In [40]:
cursor.execute("""SELECT * FROM match_teams""").fetchall()

[(1, 1, 12, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (2, 2, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (3, 3, 1, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (4, 4, 3, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (5, 5, 16, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (6, 6, 19, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (7, 7, 9, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (8, 8, 8, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (9, 9, 2, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (10, 10, 5, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (11, 11, 4, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (12, 12, 6, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (13, 13, 15, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (14, 14, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (15, 15, 18, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (16, 16, 11, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (17, 17, 13, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (18, 18, 10, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (19, 19, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (20, 20, 7, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (21, 21, 12, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (22, 22, 8, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (23, 23, 11, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (24, 24, 1, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (25, 25, 19, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (26, 26, 16, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (27, 27, 13, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (28, 28, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (29, 29, 3, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (30, 30, 2, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (31, 31, 4, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (32, 32, 7, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (33, 33, 6, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (34, 34, 9, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (35, 35, 8, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (36, 36, 17, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (37, 37, 10, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (38, 38, 15, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (39, 39, 18, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (40, 40, 5, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (41, 41, 1, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (42, 42, 11, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (43, 43, 5, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (44, 44, 12, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (45, 45, 20, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (46, 46, 19, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (47, 47, 3, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (48, 48, 13, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (49, 49, 16, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (50, 50, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (51, 51, 2, 1, 6, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (52, 52, 7, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (53, 53, 9, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (54, 54, 8, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (55, 55, 15, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (56, 56, 17, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (57, 57, 12, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (58, 58, 10, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (59, 59, 6, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (60, 60, 4, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (61, 61, 20, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (62, 62, 19, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (63, 63, 14, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (64, 64, 5, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (65, 65, 15, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (66, 66, 3, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (67, 67, 18, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (68, 68, 13, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (69, 69, 11, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (70, 70, 1, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (71, 71, 6, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (72, 72, 16, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (73, 73, 2, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (74, 74, 8, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (75, 75, 10, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (76, 76, 12, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (77, 77, 17, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (78, 78, 9, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (79, 79, 4, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (80, 80, 7, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (81, 81, 6, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (82, 82, 18, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (83, 83, 11, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (84, 84, 13, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (85, 85, 19, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (86, 86, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (87, 87, 14, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (88, 88, 3, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (89, 89, 1, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (90, 90, 5, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (91, 91, 15, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (92, 92, 12, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (93, 93, 2, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (94, 94, 17, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (95, 95, 7, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (96, 96, 10, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (97, 97, 19, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (98, 98, 16, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (99, 99, 9, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (100, 100, 4, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (101, 101, 6, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (102, 102, 3, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (103, 103, 17, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (104, 104, 18, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (105, 105, 8, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (106, 106, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (107, 107, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (108, 108, 13, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (109, 109, 1, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (110, 110, 5, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (111, 111, 15, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (112, 112, 5, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (113, 113, 2, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (114, 114, 4, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (115, 115, 7, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (116, 116, 16, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (117, 117, 3, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (118, 118, 10, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (119, 119, 9, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (120, 120, 11, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (121, 121, 19, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (122, 122, 6, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (123, 123, 8, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (124, 124, 1, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (125, 125, 13, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (126, 126, 12, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (127, 127, 18, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (128, 128, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (129, 129, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (130, 130, 10, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (131, 131, 11, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (132, 132, 5, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (133, 133, 7, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (134, 134, 9, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (135, 135, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (136, 136, 15, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (137, 137, 18, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (138, 138, 16, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (139, 139, 1, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (140, 140, 2, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (141, 141, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (142, 142, 8, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (143, 143, 13, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (144, 144, 19, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (145, 145, 14, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (146, 146, 4, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (147, 147, 2, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (148, 148, 6, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (149, 149, 3, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (150, 150, 12, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (151, 151, 10, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (152, 152, 5, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (153, 153, 9, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (154, 154, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (155, 155, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (156, 156, 18, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (157, 157, 15, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (158, 158, 11, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (159, 159, 16, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (160, 160, 1, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (161, 161, 6, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (162, 162, 7, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (163, 163, 12, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (164, 164, 9, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (165, 165, 19, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (166, 166, 8, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (167, 167, 4, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (168, 168, 2, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (169, 169, 13, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (170, 170, 3, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (171, 171, 18, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (172, 172, 16, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (173, 173, 10, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (174, 174, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (175, 175, 15, 1, 5, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (176, 176, 4, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (177, 177, 1, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (178, 178, 11, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (179, 179, 5, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (180, 180, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (181, 181, 6, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (182, 182, 2, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (183, 183, 19, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (184, 184, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (185, 185, 3, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (186, 186, 7, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (187, 187, 8, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (188, 188, 10, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (189, 189, 12, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (190, 190, 14, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (191, 191, 8, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (192, 192, 5, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (193, 193, 13, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (194, 194, 17, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (195, 195, 18, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (196, 196, 9, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (197, 197, 15, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (198, 198, 1, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (199, 199, 4, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (200, 200, 16, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (201, 201, 2, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (202, 202, 7, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (203, 203, 3, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (204, 204, 12, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (205, 205, 10, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (206, 206, 14, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (207, 207, 20, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (208, 208, 6, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (209, 209, 11, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (210, 210, 19, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (211, 211, 4, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (212, 212, 8, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (213, 213, 9, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (214, 214, 16, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (215, 215, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (216, 216, 13, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (217, 217, 15, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (218, 218, 1, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (219, 219, 18, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (220, 220, 5, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (221, 221, 12, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (222, 222, 6, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (223, 223, 10, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (224, 224, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (225, 225, 15, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (226, 226, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (227, 227, 2, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (228, 228, 3, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (229, 229, 7, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (230, 230, 11, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (231, 231, 16, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (232, 232, 4, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (233, 233, 7, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (234, 234, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (235, 235, 19, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (236, 236, 11, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (237, 237, 9, 1, 3, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (238, 238, 8, 1, 4, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (239, 239, 18, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (240, 240, 5, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (241, 241, 2, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (242, 242, 14, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (243, 243, 4, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (244, 244, 3, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (245, 245, 6, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (246, 246, 10, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (247, 247, 13, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (248, 248, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (249, 249, 1, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (250, 250, 12, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (251, 251, 17, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (252, 252, 11, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (253, 253, 18, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (254, 254, 8, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (255, 255, 7, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (256, 256, 9, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (257, 257, 15, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (258, 258, 19, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (259, 259, 16, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (260, 260, 2, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (261, 261, 6, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (262, 262, 12, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (263, 263, 20, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (264, 264, 3, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (265, 265, 13, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (266, 266, 14, 1, 0, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (267, 267, 16, 1, 2, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (268, 268, 19, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (269, 269, 1, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (270, 270, 5, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),
 (271, 271, 4, 1, 1, None, '2021-07-15 06:18:56', '2021-07-15 06:18:56'),

In [45]:
df.to_pickle('Data/df.pkl')

In [46]:
df_players.to_pickle('Data/players.pkl')

In [47]:
df_teams.to_pickle('Data/df_teams.pkl')